name: Terraform

on: push

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.26

    - name: Run tflint
      run: make tflint
    - name: Run terraform validate
      run: make validate
      env:
        AWS_REGION: us-east-1
